import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.en;
}

const translations = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      updates: 'Updates',
      contact: 'Contact',
    },
    hero: {
      tag: 'POWERING THE FUTURE',
      title_prefix: 'Ybhsoft',
      title_suffix: 'Innovation',
      subtitle: 'Turning Ideas Into Reality',
      cta_explore: 'Explore Work',
      cta_contact: 'Contact Us',
    },
    about: {
      title_line1: "We Don't Just Code.",
      title_line2: "We Architect Future.",
      p1_pre: "At ",
      p1_strong: "Ybhsoft Innovation",
      p1_post: ", we believe that technology is the ultimate canvas. Our mission \"Turning ideas into reality\" isn't just a slogan; it's our daily protocol.",
      p2: "From complex backend systems to dazzling frontend interfaces, we bridge the gap between abstract concepts and tangible, high-performance digital solutions.",
      cards: {
        speed_title: 'Speed', speed_desc: 'Rapid prototyping to production.',
        tech_title: 'Tech', tech_desc: 'Cutting-edge stack mastery.',
        global_title: 'Global', global_desc: 'Solutions without borders.',
      },
      chart_title: "Innovation Radar"
    },
    projects: {
      title: 'Recent Updates',
      desc: 'Stay tuned with our latest activities, changelogs, and announcements.',
      link: 'Open in new tab'
    },
    footer: {
      rights: 'Ybhsoft Innovation',
      tagline: 'Turning ideas into reality, one pixel at a time.',
      disclaimer: 'Some elements of this page are generated by AI, for reference only.'
    },
    chat: {
      title: 'Ybhsoft AI Assistant',
      welcome: 'Hello! I represent Ybhsoft Innovation. How can I help you today?',
      placeholder: 'Ask about our team...',
      error: 'Sorry, I lost connection to the server.',
      you: 'You'
    }
  },
  zh: {
    nav: {
      home: '首页',
      about: '关于',
      updates: '动态',
      contact: '联系',
    },
    hero: {
      tag: '赋能未来',
      title_prefix: '燧标',
      title_suffix: '创新',
      subtitle: '将创意变为现实',
      cta_explore: '探索作品',
      cta_contact: '联系我们',
    },
    about: {
      title_line1: "不仅仅是代码。",
      title_line2: "我们架构未来。",
      p1_pre: "在 ",
      p1_strong: "燧标创新 (Ybhsoft)",
      p1_post: "，我们相信技术是终极的画布。我们的使命“将创意变为现实”不仅是一句口号，更是我们的日常准则。",
      p2: "从复杂的后端系统到炫酷的前端界面，我们弥合了抽象概念与高性能数字解决方案之间的鸿沟。",
      cards: {
        speed_title: '速度', speed_desc: '从原型到生产的快速迭代。',
        tech_title: '技术', tech_desc: '前沿技术栈的极致掌控。',
        global_title: '全球', global_desc: '无国界的解决方案。',
      },
      chart_title: "创新雷达"
    },
    projects: {
      title: '最新动态',
      desc: '关注我们的最新活动、更新日志和公告。',
      link: '在新标签页打开'
    },
    footer: {
      rights: '燧标创新',
      tagline: '将创意变为现实，积跬步以至千里。',
      disclaimer: '该页面部分元素由ai生成，仅供参考'
    },
    chat: {
      title: '燧标创新 AI 助手',
      welcome: '您好！我是燧标创新的AI助手。有什么可以帮您？',
      placeholder: '询问关于我们团队...',
      error: '抱歉，我与服务器失去连接。',
      you: '您'
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};